pull_request_rules:
  - name: Automatically merge pull requests on approval ✅
    conditions:
      - or:
          - "#approved-reviews-by>=1"
          - author=hllywluis
      - check-success=build
    actions:
      merge:
        method: merge
      delete_head_branch: true
