pull_request_rules:
  - name: Add label on conflict
    conditions:
      - or:
          - author=dependabot[bot]
          - author=hllywluis
      - conflict
    actions:
      comment:
        message: '@{{author}} this pull request has conflicts that need to be resolved'
      label:
        add:
          - conflict

  # Security specific rules
  - name: Warn on high risk dependencies
    conditions:
      - author=dependabot[bot]
      - label~=security
      - label~=high-risk
    actions:
      comment:
        message: |
          ⚠️ This PR updates dependencies with security implications.
          Please review carefully before merging.

  - name: Automatic approve and merge for Dependabot and hllywluis
    conditions:
      - or:
          - author=dependabot[bot]
          - author=hllywluis
      - base=main
      - check-success=CodeQL
      - label!=do-not-merge
      - -conflict
      - -draft
    actions:
      review:
        type: APPROVE
        message: Automatically approving PR
      queue:

queue_rules:
  - name: default
    queue_conditions:
      - or:
          - author=dependabot[bot]
          - author=hllywluis
      - base=main
      - check-success=CodeQL
      - label!=do-not-merge
      - -conflict
      - -draft
    merge_conditions:
      - check-success=CodeQL
    commit_message_template: |
      {{title}} (#{{number}})

      {{body}}
    merge_method: squash
