
pull_request_rules:
  - name: Add label on conflict
    conditions:
      - or:
          - author=dependabot[bot]
          - author=hllywluis
      - conflict
    actions:
      comment:
        message: "@{{author}} this pull request has conflicts that need to be resolved"
      label:
        add:
          - conflict

  # Security specific rules
  - name: Warn on high risk dependencies
    conditions:
      - author=dependabot[bot]
      - label~=security
      - label~=high-risk
    actions:
      comment:
        message: |
          ⚠️ This PR updates dependencies with security implications.
          Please review carefully before merging.

  - name: Automatic merge for Dependabot pull requests + Automatic merge for hllywluis
    conditions: []
    actions:
      queue:
queue_rules:
  - name: duplicated default from Automatic merge for Dependabot pull requests
    queue_conditions:
      - author=dependabot[bot]
      - base=main
      - check-success=CodeQL
      - "#approved-reviews-by>=1"
      - label!=do-not-merge
      - -conflict
      - -draft
    merge_conditions:
      - check-success=CodeQL
    commit_message_template: |
      {{title}} (#{{number}})

      {{body}}
    merge_method: squash
  - name: duplicated default from Automatic merge for hllywluis
    queue_conditions:
      - author=hllywluis
      - base=main
      - check-success=CodeQL
      - label!=do-not-merge
      - -conflict
      - -draft
    merge_conditions:
      - check-success=CodeQL
    commit_message_template: |
      {{title}} (#{{number}})

      {{body}}
    merge_method: squash
