pull_request_rules:
  - name: Automatically merge pull requests on approval ✅
    conditions:
      - or:
          - "#approved-reviews-by>=2"
          - author=hllywluis
      - and:
          - check-success=build
          - check-success=CodeQL
    actions:
      review:
        type: APPROVE
        message: "Automatically approving pull request based on successful checks."
      merge:
        method: merge
      delete_head_branch:
  - name: Automatic approval for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot pull request.
