name: Sourcegraph SCIP

on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]
  schedule:
    - cron: "43 20 * * 6"

jobs:
  lsif-node:
    # this line will prevent forks of this repo from uploading lsif indexes
    if: github.repository == 'hllywluis/kleptonix'
    runs-on: ubuntu-latest
    container: node:current-alpine
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: apk add git && yarn global add @sourcegraph/scip-typescript @sourcegraph/src --ignore-engines && yarn install --ignore-engines && git config --global --add safe.directory /__w/kleptonix/kleptonix
      - name: Generate LSIF data
        run: scip-typescript index .
      - name: Upload LSIF data
        # this will upload to Sourcegraph.com, you may need to substitute a different command
        # by default, we ignore failures to avoid disrupting CI pipelines with non-critical errors.
        run: src lsif upload -github-token=${{ secrets.GITHUB_TOKEN }}
