name: Sourcegraph LSIF

on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]
  schedule:
    - cron: "43 20 * * 6"

jobs:
  lsif-node:
    # this line will prevent forks of this repo from uploading lsif indexes
    if: github.repository == 'hllywluis/kleptonix'
    runs-on: ubuntu-latest
    container: sourcegraph/lsif-node:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install --ignore-engines
      - name: Generate LSIF data
        run: lsif-tsc -p .
      - name: Upload LSIF data
        # this will upload to Sourcegraph.com, you may need to substitute a different command
        # by default, we ignore failures to avoid disrupting CI pipelines with non-critical errors.
        run: src lsif upload -github-token=${{ secrets.GITHUB_TOKEN }}
